spring: 
  application:
    name: user-management-service
    
    
server: 
  port: 8084
  
  
eureka: 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka 